trigger:
  batch: true
  branches:
    include:
      - main
      - rel/*

pr:
  branches:
    include:
      - main
      - rel/*
  
variables:
  - template: eng/common-variables.yml

stages:
  - stage: build
    displayName: Build
    jobs:
    - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}: # , eq(variables['Build.SourceBranch'], 'refs/heads/main')
      - template: /eng/common/templates/job/onelocbuild.yml
        parameters:
          CreatePr: false
          CeapexPat: $(ceapex-oneloc-pat)
          GithubPat: $(testplatform-bot-github-pat)
          AutoCompletePr: true
          UseCheckedInLocProjectJson: true
          GitHubOrg: microsoft
          locProj: Localize/LocProject.json
          
    - job: Dummy
      timeoutInMinutes: 90
      pool:
        ${{ if eq(variables._RunAsPublic, True) }}:
          vmImage: windows-latest
        ${{ if eq(variables._RunAsInternal, True) }}:
          name: VSEngSS-MicroBuild2019-1ES
          demands: Cmd
      steps:
        - powershell: |
            reg DELETE "HKLM\Software\Microsoft\StrongName\Verification" /f
            reg ADD "HKLM\Software\Microsoft\StrongName\Verification\*,*" /f
            reg DELETE "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification" /f
            reg ADD "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification\*,*" /f
          displayName: 'Disable strongname validation'