parameters:
- name: isRTM
  displayName: "Release an RTM version?"
  type: boolean
  default: false

trigger:
  batch: true
  branches:
    include:
      - main
      - rel/*

pr:
  branches:
    include:
      - main
      - rel/*

variables:
  - template: /eng/pipeline/common-variables.yml
  - name: EnableLoc
    value: true
  - name: Build.Repository.Clean
    value: true

stages:

- stage: Build
  jobs:

  # Windows
  - template: /eng/pipeline/build.yml
    parameters:
      name: Windows
      skipTests: $(SkipTests)
      isRTM: ${{ parameters.isRTM }}

- ${{ if and(eq(variables.EnableLoc, True), ne(variables._RunAsPublic, True)) }}: # ne(variables._RunAsPR, 'true'), eq(variables['Build.SourceBranch'], 'refs/heads/main')
  - stage: OneLocBuild
    displayName: Publish localizable content to OneLocBuild
    jobs:
    - template: /eng/common/templates/job/onelocbuild.yml
      parameters:
        CreatePr: false
        AutoCompletePr: true
        UseCheckedInLocProjectJson: true
        GitHubOrg: microsoft

- ${{ if and(ne(variables._RunAsPublic, True), ne(variables._RunAsPR, True)) }}:
  - stage: PublishAssetRegistry
    displayName: Publish to Build Asset Registry
    dependsOn: Build
    jobs:
    - template: /eng/common/templates/job/publish-build-assets.yml
      parameters:
        publishUsingPipelines: true
        pool:
          name: VSEngSS-MicroBuild2019-1ES
          demands: Cmd

